### ISSUE TITLE
Spring Boot 2.0.0.M3 and TestNG?

### ISSUE THREAD

**Issue by evainga** [evainga/rememberbrall#1]
https://github.com/evainga/rememberbrall/blob/90972e9c714bbd5bd77d087a8c5df1ad5f5f9d72/src/test/java/de/rememberbrall/RememberbrallIt.java#L29

@mle-enso when I try to execute this test, eclipse tells me this: 

> Could not resolve artifact org.springframework.boot:spring-boot-dependencies:pom:2.0.0.M3
> Missing org.springframework.boot:spring-boot-dependencies:pom:2.0.0.M3

Is there a problem with Spring Boot 2.0.0.M3 and testNG or did I miss anything else?

**Comment by mle-enso** [comment]
```mvn clean verify``` with a freshly cloned repo works like a charm. So does Travis.
What exactly do you execute in your IDE?

**Comment by mle-enso** [comment]
Ah I see... with ```mvn clean verify``` there are currently no integration tests executed... you miss the ```https://maven.apache.org/surefire/maven-failsafe-plugin/usage.html``` plugin in your pom.xml!

**Comment by evainga** [comment]
ahhh slipped out with my finger on the close button, didnt mean to do that ;-)

I added mvn failsafe now with TestNG, but still the same

**Comment by mle-enso** [comment]
No your plugin config still is not correct as the respective IT test still did not run in the latest Travis build.
Double-check and fix this.
https://travis-ci.org/evainga/rememberbrall

**Comment by mle-enso** [comment]
By the way... the reason is the non-conform naming of your IT test class. Try to figure out what is wrong with the plugin documentation linked above!
