### ISSUE TITLE
Readme hint not working

### ISSUE THREAD

**Issue by mle-enso** [evainga/rememberbrall#10]
The Heroku URL answers with a "Whitelabel Error Page" instead of a welcome page of your server.

**Comment by mle-enso** [comment]
Consider adding a request mapping for "/".

**Comment by evainga** [comment]
...so my idea was, as long as I don't have a nice welcome page, I could just forward the REST documentation there, as it decribes rememberbrall very well. I tried this out in my branch forward.

Locally it works well with `mvn clean package spring-boot:run`
On heroku however, the snippets can't be found, which makes it look like it is currently on rememberbrall.herokuapp.com.
`Snippet curl-request not found at /tmp/build_1cde22406b2ea026bcfac9474cfaeaaf/target/generated-snippets/show-entries/curl-request.adoc for operation show-entries`
When i locally do mvn clean package, the snippets are exactly at that place. Is it a timing problem with the REST tests? But according to this page https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html the test phase - in which the rest tests should happen according to my pom - is before the packaging phase...?

**Comment by mle-enso** [comment]
The REST documentation is not part of the packaged and bundled artifact. There is no straight forward way to deliver it with your server artifact.

**Comment by mle-enso** [comment]
What do you think about the following approach:

Right now you get familiar with Spring Boot Actuator, enable it like shown here: http://www.baeldung.com/spring-boot-actuators and provide for the request mapping "/" a tiny endpoint which redirects to the /mapping actuator which offers a list of all known request mapping to the user. This could be a nice start if somebody does not know where to start with your app/server,

Next you create a ticket for your wish above, to really bundle your generated REST Docs and provide them through a dedicate endpoint – but as already said, this comes with a little larger research phase.

**Comment by mle-enso** [comment]
Further hints for the Actuator approach could be:

- a working project with actuators at http://localhost:8080/actuator – https://github.com/mle-enso/sandbox
- hints for redirecting, especially lean is the second way described here https://stackoverflow.com/a/17961336

**Comment by evainga** [comment]
This issue has already been solved on the current master, so I'm closing the issue
