### ISSUE TITLE
Setting up mongodb for local and production stages

### ISSUE THREAD

**Issue by evainga** [evainga/rememberbrall#12]
rememberbrall.heroku.com is currently live with the latest commits you can see in the branch mongodb: https://github.com/evainga/rememberbrall/tree/mongodb
This works in heroku live version, however, the travis build failed as well as local builds fail. This is because i out commented `spring.data.mongodb.database=demo` to make `spring.data.mongodb.uri=${MONGODB_URI}` work for heroku.

So, which mongo should ideally interact on which stage with rememberbrall? Would it be good to use the same database for different stages - local, travis (=testing?) and in heroku (=production)? Because currently, the placeholder I use in heroku is not known locally and in travis.

> Description:
> Binding to target [Bindable@1cf0cacc type = java.lang.String, value = 'provided', annotations = array<Annotation>[[empty]]] failed:
>     Property: spring.data.mongodb.uri
>     Value: ${MONGODB_URI}
>     Origin: class path resource [application.properties]:7:25
>     Reason: Could not resolve placeholder 'MONGODB_URI' in value "${MONGODB_URI}"

Or - if every stage should have their own database (which I think they should), then the better question is: **How can I define the distinction for the stages in application.properties?**

**Comment by mle-enso** [comment]
For a first approach to this environment-specific issue take a look in this answer and give it a try:
https://stackoverflow.com/a/32197312

**Comment by evainga** [comment]
I now use application-local.properties and application-production.properties. You can see the result in the branch mongodb.

However the solution has some minor flaws:
1. Whenever I want to use the app locally I have to add `-Dspring.profiles.active=local` in the bash command or else the default mongo is used which means "test" instead of "demo"-db
2. The mvn clean verify process in Travis CI is now using the `-Dspring.profiles.active=local` profile 
3. After pushing stuff to heroku master, I need to configure it with `config:set SPRING_PROFILES_ACTIVE=production` so that it uses the new production properties

Is there a better way for a default handling of the properties, so that I don't have to always define them manually?

**Comment by evainga** [comment]
I could also delete the whole local profile and just use the production profile for heroku. Then the application always uses a local "test" db per default... But on the other hand I think it is nice to explititly define a db-name which should be used by the app on local stages while a production one is also defined.

**Comment by mle-enso** [comment]
First a question: What is the meaning of ```Procfile```?

Profile ```local``` in conjunction with Travis does not seem right. Also that you have to add this continuously during local development is a flaw, you're right.

So why not just using an environment-agnostic application.properties for local development and Travis integration and a application-production.properties for the Heroku environment as it is right now?

**Comment by evainga** [comment]
A Procfile is a file in which process types are declared which are run on the heroku dynos. I now know that my tryout with the spring boot profile wasn't at all well placed there...

I liked your idea with only a application.production. And with your uri-hint it works now!

**Comment by mle-enso** [comment]
Superb!
