### ISSUE TITLE
Surefire plugin should not execute integration tests

### ISSUE THREAD

**Issue by mle-enso** [evainga/rememberbrall#14]
https://github.com/evainga/rememberbrall/blob/a1bf9500bd551cdc9b17ebcc593281a2511beda0/pom.xml#L107

No this is not correct, integration tests should be executed by the maven-failsafe-plugin.
Refer also to its documentation https://maven.apache.org/surefire/maven-failsafe-plugin/examples/inclusion-exclusion.html
General mantra:  fast running (unit) tests are covered by surefire, long running (integration) tests by failsafe. Please switch this line to the failsafe plugin config.

**Comment by evainga** [comment]
Ok, thanks, done. Tested also if my workaround with the exec-config still is necessary like that to run the IT and yes it is.
