### ISSUE TITLE
Missing SSE show case in RememberbrallController

### ISSUE THREAD

**Issue by mle-enso** [evainga/rememberbrall#15]
I am pretty sure that we already had a show case of SSE in one of our controllers. This is no longer the case.
I would love to see such an endpoint may be similar to this one
```@GetMapping(path = "/entries", produces = MediaType.APPLICATION_JSON_UTF8_VALUE)``` 
but behaving with real SSEs
```@GetMapping(path = "/entries", produces = MediaType.APPLICATION_STREAM_JSON_VALUE)```

**Comment by mle-enso** [comment]
No I am not completely satisfied.

Consider one of the following options:
* duplicate RememberbrallControllerDocumentation#showAllEntries and prove that the SSE endpoint works correctly with the request header "Accept: application/stream+json"
* add real assertions to RememberbrallControllerDocumentation#showAllEntriesReactive

…or better – implement both :-)

**Comment by evainga** [comment]
so I hope my solution is now satisfying your request? Then I would like to close the issue.

**Comment by mle-enso** [comment]
Well, as for now you've only added one more untested endpoint method. As already mentioned in my last comment there is still an integration test missing.

**Comment by mle-enso** [comment]
Now I see your latest master commit. Well, now I am completely satisfied. :-)
