### ISSUE TITLE
Reactive Streams with Webflux and Thymeleaf

### ISSUE THREAD

**Issue by evainga** [evainga/rememberbrall#5]
see https://github.com/meistermeier/reactive-thymeleaf

**Comment by evainga** [comment]
About:
https://spring.io/blog/2016/07/28/reactive-programming-with-spring-5-0-m1
https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Flux.html
https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Mono.html

Tutorial:
https://dzone.com/articles/spring-boot-reactive-tutorial

Example Project:
https://github.com/LearningByExample/reactive-ms-example

**Comment by mle-enso** [comment]
May be we start from this little sample:
https://github.com/hantsy/spring-reactive-sample/tree/master/boot-mvc-thymeleaf

**Comment by evainga** [comment]
I added a thymeleaf branch with my very first little try of implementation, knowing that it is still no good. I copied a little bit from this project; https://github.com/meistermeier/reactive-thymeleaf

**Comment by evainga** [comment]
finally Rememberbrall using Webflux and Thymeleaf is in master. Eventhough it leaves still a lot of possibilities for improvements, I will close this issue and would rather prefer toopen new issues for more detailed tasks.

**Comment by mle-enso** [comment]
May be you could sum-up the detailed steps of those "possibilities for improvements" in a new issue for obvious reasons.
