### ISSUE TITLE
Track your test coverage…

### ISSUE THREAD

**Issue by mle-enso** [evainga/rememberbrall#8]
…by using https://codecov.io as can be seen here https://github.com/mle-enso/turing-machine

**Comment by mle-enso** [comment]
Example coverage: https://codecov.io/github/mle-enso/turing-machine?branch=master

**Comment by evainga** [comment]
too many open issues here... so this one will be closed. Here is the test coverage: https://codecov.io/gh/evainga/rememberbrall

**Comment by mle-enso** [comment]
Consider adding a request mapping for "/".

**Comment by evainga** [comment]
already thought about that... but what does it have to do with my test coverage?

**Comment by mle-enso** [comment]
What comment are you referring to? ;-)

**Comment by evainga** [comment]
dont know... which one are you referring to? :P

**Comment by mle-enso** [comment]
Hehe, the accidentally added one... moved it to #10 .
